// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcupcittkjtfqqwkyqeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjdXBjaXR0a2p0ZnFxd2t5cWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODIxODYsImV4cCI6MjA3NDE1ODE4Nn0._ieM68V8BBFcSsJbCpkioY16c451otiv7ar30fUEO30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});